config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  get '/signup' => 'users#new' #current setup needed slash in front, no quotes around signup_path in home/index - signup link
  post '/signup' => 'users#create'
  get '/signin'=> 'sessions#new'
  post '/signin' => 'sessions#create'
  get 'logout' => 'sessions#logout'
  
 

  root 'home#index'



  resources :wines do 
    resources :reviews
  end 

  resources :reviews 
  

  resources :users do 
    resources :reviews 
  end 

  resources :users

  resources :likes
  
  resources :reviews do 
    resources :likes
  end

  resources :reviews do 
    put :like, on: :member
    get :like, on: :member
  end 

  


  #google login route
  get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :user_not_logged_in

    def index
        if params[:review_id]
            @review = Review.find_by(id: params[:review_id])
            @likes = @review.liked_by.uniq           
        else       
            @liked_reviews = LikedReview.all
            
            @likes = @liked_reviews.uniq{|details| details.user_id}
           
            
        end 
    end

end 

app/views/likes/index.html.erb
<% if params[:review_id] %>
    <div>

        <ul>
        <h1>Review Liked By</h1>
        <% @likes.each do |details| %>
        <li class="likesviews">
          <div>
                <p><%= details.username %></p>
                <p><%= link_to "View User Profile", user_path(details.id)%> </p>
                          
             
          </div>
        </li>
    
        <%end%>
    </ul>

</div>
<%else%>

<div class="userview">

    <h1>Review Likes</h1>
        <p><%=@likes.count%> reviews have been liked on amateur wine reviewer</p>
        <p><%=link_to "Read Reviews", reviews_path%></p>
 


<%end%>