config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  get '/signup' => 'users#new' #current setup needed slash in front, no quotes around signup_path in home/index - signup link
  post '/signup' => 'users#create'
  get '/signin'=> 'sessions#new'
  post '/signin' => 'sessions#create'
  get 'logout' => 'sessions#logout'
  
 

  root 'home#index'



  resources :wines do 
    resources :reviews
  end 

  resources :reviews 
  

  resources :users do 
    resources :reviews 
  end 

  resources :users

  resources :likes
  
  resources :reviews do 
    resources :likes
  end

  resources :reviews do 
    put :like, on: :member
    get :like, on: :member
  end 

  


  #google login route
  get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :reviews    
    has_many :wines, through: :reviews
    
    has_many :liked_reviews
    has_many :likes, through: :liked_reviews, source: :review

    accepts_nested_attributes_for :reviews

    has_secure_password

    validates :username, presence: true
    validates :username, uniqueness: true
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :favorite_wine, length: { maximum: 100 }

    def self.from_omniauth(auth)
        where(email: auth.info.email).first_or_initialize do |user|
          user.username = auth.info.name
          user.email = auth.info.email
          user.password = SecureRandom.hex
        end
      end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :user_not_logged_in, only: [:new, :create]
    
    def new 
        @user = User.new
    end 

    def create 
        @user = User.new(user_params)
      
      if @user.valid?
        @user.save
        
        session[:user_id] = @user.id
        
        redirect_to user_path(@user)
      else
        render :new
      end
    end 

    def show
        
        @user = User.find_by(id: params[:id]) 
        @reviews = Review.all
        @review = Review.find_by_id(params[:id])

    end

    def index 
        
        @users = User.all    

    end 

    def edit
       @user = current_user
        
    end
    
    def update
     
        @user = current_user   
        @user.update(email: params[:user][:email], favorite_wine: params[:user][:favorite_wine])
        redirect_to user_path(@user)
         
    end

    def user_params
        params.require(:user).permit([:username, :password, :email, :favorite_wine])
        #all attrib must be here or they won't be saved
    end

end 

app/views/users/edit.html.erb
<%= render partial: 'layouts/errors', locals: {object: @user}  %>

<div class="userview">
<h1>Edit Info</h1>
    <%= form_for @user do |f| %>
        
        <%= f.text_field :email, placeholder: @user.username %> <br>
        <%= f.text_field :favorite_wine %> <br>
        
        <%= f.submit value="Update Info" %>
    <% end %>
</div>

app/views/users/index.html.erb
<div>

    <ul id="usersul">
    <h1 id="reviewerstitle"> The Amateur Wine Reviewers </h1>
    <% @users.each do |details| %>
    <li>
        <div>
            <div class="glass">
                <p class="glasslabel"><%= details.username %></p>
                <p class="glassfav"><%= details.favorite_wine %></p>
                <p><%= link_to "View User Profile", user_path(details)%> </p>
                <%= link_to "View User Reviews", user_reviews_path(details) %>
                
            </div>
        </div>
    
    
    </li>
    
    <%end%>
    </ul>

</div>

app/views/users/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @user}  %>
<div class="userview">
    <h1>Sign Up</h1>
    <%= form_for @user do |f| %>
        <%= f.text_field :username, placeholder: "Enter a Username" %> <br>
        <%= f.text_field :email, placeholder: "Email Address" %> <br>
        <%= f.text_field :favorite_wine, placeholder: "Enter your favorite type of wine, grape, region, maker etc." %> <br>
        <%= f.password_field :password, placeholder: "Choose a password"%> <br>
        <p class="diffsubmit"><%= f.submit %></p>

        <p> - or - </p>
        <!-- <p id="googlein"><%= link_to "Sign Up with Google", '/auth/google_oauth2' %></p> -->
        <p id="googlein"><a href="/auth/google_oauth2"><img src="https://developers.google.com/identity/images/btn_google_signin_dark_normal_web.png"></a></p>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="userview">
    <div id="userdetails">
        <p>Username: <%= @user.username %></p>
    
        <p>Favorite Wine: <%= @user.favorite_wine %></p> 
        
        <p><%= @user.username %>'s Wine Reviews</p>
        <ul id="reviewsul">
        <% @user.reviews.each do |details| %>
            <li>
            <%= details.title %>
            <%= link_to "view review", review_path(details) %>
            </li>
            <%end%>
           </ul>

    <div id="useredit" class="alllinks">
        <% if @user == current_user %>
        

        <p><%= link_to "Edit Info", edit_user_path(@user) %> </p>
        <br>
        <p><%= link_to "Add Wine", new_wine_path %> </p>
        

        <% end %>
    </div>
</div>

<div class="sidebarright">
    <h3><%=@user.username%>'s Favorite Reviews: </h3>
    <ul>
    
    <% @user.likes.uniq.each do |l| %>
        <li>
        <p><%= link_to l.title, review_path(l) %></p>
    
    
        </li>
        <%end%>
    </ul>
</div>