config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  get '/signup' => 'users#new' #current setup needed slash in front, no quotes around signup_path in home/index - signup link
  post '/signup' => 'users#create'
  get '/signin'=> 'sessions#new'
  post '/signin' => 'sessions#create'
  get 'logout' => 'sessions#logout'
  
 

  root 'home#index'



  resources :wines do 
    resources :reviews
  end 

  resources :reviews 
  

  resources :users do 
    resources :reviews 
  end 

  resources :users

  resources :likes
  
  resources :reviews do 
    resources :likes
  end

  resources :reviews do 
    put :like, on: :member
    get :like, on: :member
  end 

  


  #google login route
  get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :user_not_logged_in

    def index 
        @user = User.find_by(id: params[:id])
                   
        @review = Review.find_by_id(params[:id])

        if params[:wine_id]
            @wine = Wine.find_by(id: params[:wine_id])
            @reviews = @wine.reviews
        elsif params[:user_id]
            @user = User.find_by(id: params[:user_id])
            @reviews = @user.reviews
        else 
            @reviews = Review.all 
        end
        
    end 



    def show 
        @wine = Wine.find_by_id(params[:wine_id])
        @review = Review.find_by_id(params[:id])
    end 

    def new         
        if params[:wine_id] && @wine = Wine.find_by_id(params[:wine_id])
            @review = @wine.reviews.build
          else
            @review= Review.new
            @review.build_wine
          end
    end 

    def create       
        @wine = Wine.find_by_id(params[:wine_id])
        @review = current_user.reviews.build(review_params)

        if @review.save 
            redirect_to review_path(@review)
        else
            render :new 
        end
    end 

    def edit
        @user = current_user
        @review = Review.find(params[:id])
        if @user.id != @review.user_id
            redirect_to user_path(@user)
        end
        
    end 
       
    def like 
        @review = Review.find(params[:id])
        type = params[:type]
        if type == "like"
            
            current_user.likes << @review
                redirect_to like_review_path(current_user)

        elsif type == "unlike"
            current_user.likes.delete(@review)
             

        else
            
             
        end
    end
       


    def update 
        @review = Review.find(params[:id])
        @wine = Wine.find_by_id(params[:id])
        @wine_review = @review.wine_id

        if @review.update(review_params)
            redirect_to review_path(@review)
        else
            render :edit
        end
    end 

    def destroy 
        @user = current_user
        @review = Review.find(params[:id])

        if @user.id != @review.user_id
            redirect_to user_path(@user)
        else
            @review.destroy
            redirect_to user_path(@user)
        end
        
    end

    private 

    def review_params
        params.require(:review).permit([:title, :description, :user_id, :wine_id, :fruit, :tannin, :body, :balance, :acidity, :flavors, :other, :color, :taste, :balance_rating, :wine_experience, :someone_else_like, :total])
    end


end 

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
<% if params[:wine_id] %>
        <%= f.hidden_field :wine_id %>
      
       <% end %> 


<div class="review desc">
        
        <%= f.text_field :title, placeholder: "Name this review..."%> 
            <br>   
        <%= f.text_field :description, placeholder: "Describe the wine summarizing overall reflections and tasting notes..." %>
            <br>
        <%= f.text_field :fruit, placeholder: "Note fruit impressions..."%> 
            <br>
        <%= f.text_field :tannin, placeholder: "Note tannin impressions..."%> 
            <br> 
        
        <%= f.select :body, options_for_select(["light - aka 'skim milk'", "medium - aka '2% milk'", "heavy - aka 'whole milk"]), prompt: 'Select Body'  %> 
            <br> 
        <%= f.text_field :balance, placeholder: "Notes on overall balance and finish..."%> 
            <br>
        <%= f.text_field :acidity, placeholder: "Note acidity impressions..."%> 
            <br>
        <%= f.text_field :flavors, placeholder: "Note tastes, flavors, scents, etc..."%> 
            <br>
        <%= f.text_field :other, placeholder: "Note anything else you would like..."%> 
            <br>
    </div>
        

    <div class="review rating">
        <h4>Rate the Wine - Rate each category 1 through 5</h4>        
        
        <%= f.number_field :color, placeholder: "Give a color rating" %>
        <br>
        
        <%= f.number_field :taste, placeholder: "Rate the tastes" %>
        <br>
        
        <%= f.number_field :balance_rating, placeholder: "Rate the balance" %>
        <br>
        
        <%= f.number_field :wine_experience, placeholder: "Rate the overall wine experience" %>
        <br>
        
        <%= f.number_field :someone_else_like, placeholder: "Even if you don't like it, could someone else?" %>
        <br>
        
    </div>

  <%= f.submit%>
  <% end %>
  

app/views/reviews/edit.html.erb
<%= render partial: 'layouts/errors', locals: {object: @review}  %>
<div class="userview">
    <h1> Edit the Review </h1>
        
 
    <%= render partial: 'form'%>
    
</div>

app/views/reviews/index.html.erb
<ul id="reviewsul">
<div><h1>The Wine Reviews</h1>
    <% @reviews.each do |details| %>
    <li id="reviewsli" >
            
            <p><%= details.title %></p>
            <p><%= link_to "View this Review", review_path(details)%> </p>           
        
        
            
    </li>
    <% end %>
    </ul>
    
</div>

app/views/reviews/like.html.erb
<div id="likedreviews">
<h1>the liked reviews page</h1>
<ul>
<% current_user.likes.uniq.each do |l| %>
<li id="likereviewsli">
    <p id="reviewsbuttons">View: <%= link_to l.title, review_path(l) %></p>
    
    
</li>
<%end%>
</ul>
</div>

app/views/reviews/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @review}  %>
<div class="userview">
    <h1> Review <%= @wine.wine_name %></h1>
        
 
    <%= render partial: 'form'%>
    
</div>

app/views/reviews/show.html.erb
<div id="showwinereview">
<h1>Review of <%= @review.wine.wine_name%></h1>
<div>
        <p><%= @review.title %></p>
        <p><%= @review.description %></p>
        <p>Fruit <%= @review.fruit %></p>
        <p>Tannin: <%= @review.tannin %></p>
        <p>Body: <%= @review.body %>%</p>
        <p>Balance: <%= @review.balance %></p>
        <p>Acidity: <%= @review.acidity %></p>
        <p>Flavors: <%= @review.flavors %></p>
        <p>Other Notes: <%= @review.other %></p>

        <p>Ratings</p>
        <p>Color: <%= @review.color %></p>
        <p>Taste: <%= @review.taste %></p>
        <p>Balance: <%= @review.balance_rating %></p>
        <p>The Wine Experience: <%= @review.wine_experience %></p>
        <p>Some Else Might like it Rating: <%= @review.someone_else_like %></p>
        <% @review.total = @review.color + @review.taste + @review.balance_rating + @review.wine_experience + @review.someone_else_like %>
        <% @rating = (@review.total / 25) * 100 %>
    
        <p>This Amatuer Wine review gives this wine <%= @rating %> points!</p>
        
               
    </div>
    <div>
    <p><%= link_to "See Likes of Review", review_likes_path(@review) %>
    </div>

    <div>
        <% if current_user %>
            <p id="likebutton"><%= link_to "like",   like_review_path(@review, type: "like"), method: :put %><i class="fas fa-heart"></i></p>
            <p id="unlikebutton"><%= link_to "unlike", like_review_path(@review, type: "unlike"), method: :put %><i class="fas fa-heart-broken"></i></p>
            
        <% end %>
    </div>

    <div>
        
            <% if @review.user_id == current_user.id %>
            
        

            <p id="reviewsbuttons"><%= link_to "Edit Review", edit_wine_review_path(@review) %></p>
            <p id="reviewsbuttons"><%= link_to 'Destroy', @review, method: :delete %></p>

        

        <% end %>
    
    </div>

</div>