config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  get '/signup' => 'users#new' #current setup needed slash in front, no quotes around signup_path in home/index - signup link
  post '/signup' => 'users#create'
  get '/signin'=> 'sessions#new'
  post '/signin' => 'sessions#create'
  get 'logout' => 'sessions#logout'
  
 

  root 'home#index'



  resources :wines do 
    resources :reviews
  end 

  resources :reviews 
  

  resources :users do 
    resources :reviews 
  end 

  resources :users

  resources :likes
  
  resources :reviews do 
    resources :likes
  end

  resources :reviews do 
    put :like, on: :member
    get :like, on: :member
  end 

  


  #google login route
  get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/models/wine.rb
class Wine < ActiveRecord::Base
    has_many :reviews
   
    has_many :users, through: :reviews

    accepts_nested_attributes_for :reviews

    validates :wine_name, presence: true
    
    validates :vintage, length: { is: 4 }
    validates :wine_name, length: { maximum: 100 }
    validates :winemaker, length: { maximum: 100 }
    validates :vineyard, length: { maximum: 100 }
    validates :region, length: { maximum: 100 }
    validates :alcohol, length: { maximum: 5 } 
    validates :story, length: { maximum: 1000 }
    validate :wine_and_vintage 

   
    
    scope :styles, -> (style) {where(style: style)}
    def self.styles(style)
        where(style: style)
    end 
   

    def wine_and_vintage 
        wine = Wine.find_by(wine_name: wine_name, vintage: vintage)
        if !!wine && wine != self 
            errors.add(:vintage, 'has been added, choose a different wine or different vintage')
        end 
    end 
end 

app/controllers/wines_controller.rb
class WinesController < ApplicationController
    before_action :user_not_logged_in
    
    def show
        @wine = Wine.find(params[:id])
        @wine_reviews = @wine.reviews
    end

    def index 
       

        if params[:style] != nil
            @style = params[:style]
            @wines = Wine.styles(@style)
        else
            @wines = Wine.all
        end

    end 

    def new 
        @wine = Wine.new
    end 

    def create
        @wine = Wine.new(wine_params)
        if @wine.save 
            
            redirect_to wine_path(@wine)
        else
            render :new 
        end
    end 

    
    def edit
        @wine = Wine.find(params[:id])
    end 

    def update 
        @wine.update(wine_params)
        if @wine.save
            redirect_to @wine
        else
            render :edit
        end
    end 

    

    private 

    def wine_params
        params.require(:wine).permit([:wine_name, :vintage, :vineyard, :winemaker, :story, :grape, :region, :style, :alcohol, :store_id])
    end

end 

app/views/wines/_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: @wine}  %>
<%= form_for @wine do |f| %>

    <%= f.text_field :wine_name, placeholder: "Enter the wine name"%> 
        <br>   
    <%= f.number_field :vintage, placeholder: "Enter vintage, (that's Year for the Novice)" %>
        <br>
    <%= f.select :style, options_for_select(["rose", "bordeaux", "burgundy", "meritage", "sparkling", "red", "white", "other"]), prompt: 'Select Wine Type or Style'  %> 
        <br> 
    <%= f.text_field :grape, placeholder: "Enter the grape or grapes, add percentages if possible or known"%> 
        <br> 
    <%= f.number_field :alcohol, placeholder: "Enter the alcohol percentage" %>
        <br>
      <%= f.text_field :region, placeholder: "Enter the Region"%> 
        <br> 
    <%= f.text_field :vineyard, placeholder: "Enter the Vineyard"%> 
        <br>
    <%= f.text_field :winemaker, placeholder: "Enter the Wine Maker"%> 
        <br> 
    <%= f.text_area :story, placeholder: "'Stories sell wine!-' A quote by Larry Tse, enter some notes, history or special topics about the wine, wine maker, region, vineyard or grape"%> 
        <br>
  <%= f.submit%>
  

<% end %>

app/views/wines/edit.html.erb
<div class="userview">
<h1>Edit Wine</h1>
<%= render partial: 'form'%>
</div>

app/views/wines/index.html.erb
<%= form_tag("/wines", method: "get") do %>
                <%= select_tag "style", options_for_select(["rose", "bordeaux", "burgundy", "meritage", "sparkling", "red", "white"]), prompt: 'Filter by style or type of wine' %>
 
                <%= submit_tag "Filter" %>
                <% end %>

<div>
    <ul id="winesul">
        <div id="thewines">
            <h1>The Wines</h1>
                
                
    <% @wines.each do |details| %>
    
    <li id="winesli">
    <div class="wholebottle">
  
        <div class="top">
            <p class="lip"></p>
            <p class="foilcutline"></p>
            <p class="foil"></p>
            <p class="neck"></p>
        </div>

        <div class="bottle main">
            <p></p>
            <p class="label">
                <div>
                    <p id="winename"><%= details.wine_name %></p>
       
                    <p id="vintage"><%= details.vintage %></p>
       
                    <p id="winestyle"><%= details.style %></p>
                </div>
            </p>    
        </div>
  
        </div>
        <%= link_to "View Wine", wine_path(details)%>
        </li>
        
        <% end %>
        </ul>
    
    </div>

app/views/wines/new.html.erb
<div class="userview">
<h1>Add a Wine</h1>
<%= render partial: 'form'%>
</div>

app/views/wines/show.html.erb
<div class="userview">
    <div>
        <p>Wine: <%= @wine.wine_name %></p>
        <p>Vintage: <%= @wine.vintage %></p>
        <p>Style: <%= @wine.style %></p>
        <p>Grape: <%= @wine.grape %></p>
        <p>Alcohol: <%= @wine.alcohol %>%</p>
        <p>Region: <%= @wine.region %></p>
        <p>Vineyard: <%= @wine.vineyard %></p>
        <p>Winemaker: <%= @wine.winemaker %></p>
        <p>Story: <%= @wine.story %></p>
               
    </div> 
    <div class="listreviews">
          <ul>
            <% @wine_reviews.each do |list| %>
                <li>
                    <%= link_to list.title, review_path(list) %>
                </li>
            <%end%>
        </ul> 
    </div>
            

    <div id="useredit" class="alllinks">
        <p><%= link_to "View Reviews", wine_reviews_path(@wine) %></p>
        <br>
        <p><%= link_to "Edit Wine", edit_wine_path(@wine) %></p>
        <br>
        <p><%= link_to "Review this Wine", new_wine_review_path(@wine) %></p>
        

    </div>

</div>